# Версия docker-compose
version: '3'

# Список наших сервисов (контейнеров)
services:

#  ktor-web-app:
#    restart: always
#    container_name: ktor-web-app
#    build:
#      dockerfile: Dockerfile
#      context: ./backend
#    environment:
#      - VIRTUAL_HOST=anilibria.io
#      - LETSENCRYPT_HOST=anilibria.io
#    ports:
#      - 4060:4060
#    expose:
#      - 4060
#    networks:
#      - app-network
#    volumes:
#      - ./docker/data/app:/app/ktorlog

#  nginx:
#    # используем последний стабильный образ nginx
#    image: nginx:1.15
#    restart: unless-stopped
#    # маршрутизируем порты
#    ports:
#      - 80:80
#      #- 443:443
#    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
#    volumes:
#      - ./docker/services/nginx:/etc/nginx/conf.d
#      - ./docker/www:/var/www
#      - ./docker/data/nginx:/var/log/nginx
#    depends_on:
#      - ktor-web-app
#    networks:
#      - app-network

  mariadb:
    container_name: mariadb
    image: mariadb:10.3
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ./docker/service/mariadb/my.cnf:/etc/mysql/conf.d/my1.cnf
      - ./docker/data/mariadb:/var/lib/mysql
      - ./docker/www/sql/main.sql:/docker-entrypoint-initdb.d/01-main.sql
    environment:
      - MYSQL_USER=mysqlusr
      - MYSQL_PASSWORD=mysqlpwd
      - MYSQL_ROOT_PASSWORD=mysqlrootpwd
      - MYSQL_DATABASE=mysqldb
#    networks:
#      - db-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mariadb
    environment:
#      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
#      - PMA_PORT=3308
      - MYSQL_ROOT_PASSWORD=mysqlrootpwd
    ports:
      - 8181:80
    volumes:
      - ./docker/service/phpmyadmin:/etc/phpmyadmin
#    networks:
#      - db-network

networks:
  app-network:
#    driver: bridge
  db-network:
#    driver: bridge